apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bn48m7qjm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bn48m7qjm-go 
  name: bn48m7qjm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bn48m7qjm-go 
